from collections.abc import Callable
from dataclasses import dataclass
from enum import Enum
from typing import Any, Self

# ============================================================================
# HTTP Core
# ============================================================================

class Request:
    """Zero-copy HTTP request structure."""
    path: str
    method: str
    query_string: str
    path_params: dict[str, str]
    query_params: dict[str, str]
    headers: dict[str, str]
    ip: str | None
    ips: list[str]
    xhr: bool
    secure: bool
    hostname: str | None
    url: str
    original_url: str
    protocol: str

    def query(self, name: str) -> str | None: ...
    def param(self, name: str) -> str | None: ...
    def header(self, name: str) -> str | None: ...
    def accepts(self, types: list[str]) -> str | None: ...
    def accepts_json(self) -> bool: ...
    def accepts_html(self) -> bool: ...
    def subdomains(self) -> list[str]: ...
    def cookie(self, name: str) -> str | None: ...
    def cookies(self) -> dict[str, str]: ...
    def body_bytes(self) -> bytes: ...
    def json(self) -> Any: ...
    def content_type(self) -> str | None: ...
    def is_content_type(self, content_type: str) -> bool: ...
    def is_json(self) -> bool: ...
    def is_form(self) -> bool: ...
    def is_multipart(self) -> bool: ...
    def form(self) -> FormData: ...
    def file(self, name: str) -> UploadedFile | None: ...
    def files(self) -> list[UploadedFile]: ...
    def fresh(self, etag: str | None, last_modified: str | None) -> bool: ...
    def stale(self, etag: str | None, last_modified: str | None) -> bool: ...


class Response:
    """Express.js-compatible HTTP response writer."""
    status_code: int
    headers_sent: bool
    finished: bool

    def status(self, status: int) -> Response: ...
    def header(self, key: str, value: str) -> Response: ...
    def set(self, key: str, value: str) -> Response: ...
    def get(self, key: str) -> str | None: ...
    def remove_header(self, key: str) -> Response: ...
    def headers(self, headers: dict[str, str]) -> Response: ...
    def append(self, key: str, value: str) -> Response: ...
    def vary(self, field: str) -> Response: ...
    def links(self, links: dict[str, str]) -> Response: ...
    def location(self, url: str) -> Response: ...
    def etag(self, value: str) -> Response: ...
    def last_modified(self, date: str) -> Response: ...
    def expires(self, date: str) -> Response: ...
    def content_type(self, mime_type: str) -> Response: ...
    def type(self, mime_type: str) -> Response: ...
    def body(self, body: bytes) -> Response: ...
    def body_str(self, body: str) -> Response: ...
    def write(self, data: bytes) -> Response: ...
    def append_body(self, data: bytes) -> Response: ...
    def finish(self) -> None: ...
    def end(self, data: str | bytes | None = None) -> Response: ...
    def send_status(self, status: int) -> Response: ...
    # ExpressJS-like methods
    def send(self, data: str | bytes | None) -> Response: ...
    def json(self, data: Any) -> Response: ...
    def html(self, content: str) -> Response: ...
    def text(self, content: str) -> Response: ...
    def xml(self, content: str) -> Response: ...
    def redirect(self, url: str, status: int = 302) -> Response: ...
    def cookie(
        self,
        name: str,
        value: str,
        max_age: int | None = None,
        path: str | None = None,
        domain: str | None = None,
        secure: bool = False,
        http_only: bool = False,
        same_site: str | None = None,
    ) -> Response: ...
    def clear_cookie(
        self,
        name: str,
        path: str | None = None,
        domain: str | None = None,
    ) -> Response: ...
    def cache_control(
        self,
        max_age: int = 0,
        private: bool = False,
        no_cache: bool = False,
        no_store: bool = False,
    ) -> Response: ...
    def no_cache(self) -> Response: ...
    def cors(
        self,
        origin: str = "*",
        methods: list[str] | None = None,
        headers: list[str] | None = None,
        credentials: bool = False,
        max_age: int | None = None,
    ) -> Response: ...
    def attachment(self, filename: str | None = None) -> Response: ...
    def send_file(
        self,
        path: str,
        filename: str | None = None,
        content_type: str | None = None,
    ) -> Response: ...
    def download(self, path: str, filename: str | None = None) -> Response: ...
    # SSE/Streaming methods
    def sse(self, events: list[SSEEvent]) -> Response: ...
    def sse_collect(self, generator: Any) -> Response: ...
    def sse_stream(self, generator: Any) -> Response: ...
    def sse_event(
        self,
        data: str,
        event: str | None = None,
        id: str | None = None,
    ) -> Response: ...
    def sse_headers(self) -> Response: ...


class HeaderMap:
    """HTTP header container."""

    def get(self, key: str) -> str | None: ...
    def get_all(self, key: str) -> list[str]: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[str]: ...
    def items(self) -> dict[str, str]: ...


# ============================================================================
# File Uploads
# ============================================================================

class UploadedFile:
    """Uploaded file from a multipart form."""
    filename: str
    name: str
    content_type: str
    size: int

    def read(self) -> bytes: ...
    def read_text(self) -> str: ...
    def save(self, path: str, overwrite: bool = False) -> str: ...
    def save_to(self, directory: str) -> str: ...
    def is_image(self) -> bool: ...
    def is_video(self) -> bool: ...
    def is_audio(self) -> bool: ...
    def is_pdf(self) -> bool: ...
    def extension(self) -> str | None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...


class FormData:
    """Parsed multipart/form-data or URL-encoded form body."""

    def get(self, key: str) -> str | None: ...
    def get_or(self, key: str, default: str | None = None) -> str | None: ...
    def file(self, key: str) -> UploadedFile | None: ...
    def files_list(self, key: str) -> list[UploadedFile]: ...
    def all_files(self) -> list[UploadedFile]: ...
    def field_names(self) -> list[str]: ...
    def file_names(self) -> list[str]: ...
    def has(self, key: str) -> bool: ...
    def has_file(self, key: str) -> bool: ...
    def file_count(self) -> int: ...
    def __len__(self) -> int: ...


# ============================================================================
# Server & Routing
# ============================================================================

@dataclass
class Server:
    router: Router
    websocket_router: Any
    startup_handler: Any
    shutdown_handler: Any

    def add_route(self, route: Route) -> None: ...
    def set_router(self, router: Router) -> None: ...
    def use_middleware(self, middleware: Any) -> None: ...
    def start(
        self,
        host: str,
        port: int,
        num_processes: int,
        workers_threads: int,
        max_blocking_threads: int,
        max_connections: int,
    ) -> None: ...
    def enable_http2(self) -> None: ...
    def set_reload_config(self, config: ReloadConfig) -> None: ...
    def get_reload_manager(self) -> ReloadManager | None: ...
    def get_health_check(self) -> HealthCheck | None: ...
    def graceful_reload(self) -> None: ...
    def hot_reload(self) -> None: ...


class Route:
    """HTTP route definition."""
    path: str
    function: Callable[[Request, Response], Any]
    method: str
    doc: str | None

    def matches(self, path: str, method: str) -> str: ...
    def clone_route(self) -> Route: ...
    def update_path(self, new_path: str) -> None: ...
    def update_method(self, new_method: str) -> None: ...
    def is_valid(self) -> bool: ...
    def get_path_parans(self) -> list[str]: ...
    def has_parameters(self) -> bool: ...
    def normalized_path(self) -> str: ...
    def same_handler(self, other: Route) -> bool: ...


class Router:
    """Route registry."""
    routes: list[Route]

    def add_route(self, route: Route) -> None: ...
    def remove_route(self, path: str, method: str) -> bool: ...
    def get_route(self, path: str, method: str) -> Route | None: ...
    def get_routes_by_path(self, path: str) -> list[Route]: ...
    def get_routes_by_method(self, method: str) -> list[Route]: ...
    def extend_route(self, routes: list[Route]) -> None: ...


@dataclass
class SocketHeld:
    socket: Any


# ============================================================================
# Dependency Injection
# ============================================================================

class Context:
    """Request-scoped dependency injection context."""
    user_id: str | None
    is_authenticated: bool
    request_id: str

    def __init__(self) -> None: ...
    def set(self, key: str, value: Any) -> None: ...
    def get(self, key: str) -> Any: ...
    def has(self, key: str) -> bool: ...
    def remove(self, key: str) -> bool: ...
    def keys(self) -> list[str]: ...
    def set_auth(self, user_id: str, roles: list[str] | None = None) -> None: ...
    def clear_auth(self) -> None: ...
    def has_role(self, role: str) -> bool: ...
    def elapsed_ms(self) -> float: ...


class DIContainer:
    """Dependency injection container."""

    def __init__(self) -> None: ...
    def singleton(self, name: str, value: Any) -> None: ...
    def factory(self, name: str, factory: Callable[[], Any]) -> None: ...
    def get_singleton(self, name: str) -> Any: ...
    def create_context(self) -> Context: ...
    def has(self, name: str) -> bool: ...
    def remove(self, name: str) -> bool: ...


# ============================================================================
# Background Tasks
# ============================================================================

class TaskStatus(Enum):
    Pending = ...
    Running = ...
    Completed = ...
    Failed = ...
    Cancelled = ...


class TaskResult:
    """Result of a background task."""
    task_id: str
    status: TaskStatus
    result: str | None
    error: str | None
    started_at: float | None
    completed_at: float | None

    def is_success(self) -> bool: ...
    def is_failed(self) -> bool: ...
    def is_pending(self) -> bool: ...


class TaskExecutor:
    """Background task executor with worker pool."""

    def __init__(
        self,
        num_workers: int = 4,
        queue_size: int = 1000,
    ) -> None: ...
    def submit(
        self,
        handler: Callable[..., Any],
        args: tuple | None = None,
        delay_ms: int | None = None,
    ) -> str: ...
    def get_result(self, task_id: str) -> TaskResult | None: ...
    def is_complete(self, task_id: str) -> bool: ...
    def cancel(self, task_id: str) -> bool: ...
    def cleanup(self, max_age_secs: int) -> None: ...
    def pending_count(self) -> int: ...
    def completed_count(self) -> int: ...
    def shutdown(self) -> None: ...


# ============================================================================
# Blocking Executor (GIL-free parallel execution)
# ============================================================================

class BlockingExecutor:
    """
    High-performance, GIL-releasing thread pool executor implemented in Rust.

    Runs Python callables on dedicated Rust OS threads. The calling thread
    releases the GIL while waiting for results, enabling true parallelism
    for CPU-bound work without GIL contention.

    Supports context-manager protocol (``with`` statement) for automatic
    shutdown.
    """

    def __init__(
        self,
        max_threads: int = 0,
        queue_size: int = 0,
    ) -> None: ...

    def run_sync(self, callable: Callable[..., Any], *args: Any, **kwargs: Any) -> Any: ...
    def run_parallel(
        self,
        tasks: list[tuple[Callable[..., Any], tuple, dict[str, Any] | None]],
    ) -> list[Any]: ...
    def map(
        self,
        callable: Callable[[Any], Any],
        items: list[Any],
        chunk_size: int = 0,
    ) -> list[Any]: ...
    def active_threads(self) -> int: ...
    def pool_size(self) -> int: ...
    def pending_tasks(self) -> int: ...
    def is_running(self) -> bool: ...
    def shutdown(self, wait: bool = True, timeout_secs: float = 30.0) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...  # noqa: PYI036
    def __repr__(self) -> str: ...  # noqa: PYI029


# ============================================================================
# SSE / Streaming
# ============================================================================

class SSEEvent:
    """Server-Sent Event."""
    id: str | None
    event: str | None
    data: str
    retry: int | None

    def __init__(
        self,
        data: str,
        id: str | None = None,
        event: str | None = None,
        retry: int | None = None,
    ) -> None: ...
    def format(self) -> str: ...
    def to_bytes(self) -> bytes: ...


class SSEStream:
    """SSE stream for sending events to clients."""

    def __init__(self, buffer_size: int = 100) -> None: ...
    def send(self, event: SSEEvent) -> bool: ...
    def send_data(self, data: str) -> bool: ...
    def send_event(self, event_name: str, data: str) -> bool: ...
    def keepalive(self) -> bool: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...
    def event_count(self) -> int: ...


class SSEGenerator:
    """Generator-based SSE stream that consumes Python iterators."""

    def __init__(self) -> None: ...
    def is_exhausted(self) -> bool: ...
    def event_count(self) -> int: ...


class StreamingResponse:
    """Streaming response for large data transfers."""
    content_type: str

    def __init__(
        self,
        content_type: str = "application/octet-stream",
        buffer_size: int = 100,
    ) -> None: ...
    def write(self, data: bytes) -> bool: ...
    def write_str(self, data: str) -> bool: ...
    def write_line(self, data: str) -> bool: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...


# ============================================================================
# WebSocket
# ============================================================================

class WsMessageType(Enum):
    Text = ...
    Binary = ...
    Ping = ...
    Pong = ...
    Close = ...


class WsMessage:
    """A WebSocket message with type and payload."""
    msg_type: WsMessageType
    data: bytes

    def text(self) -> str | None: ...
    def json(self) -> Any: ...


class RustWebSocket:
    """Rust-backed WebSocket connection."""

    def send_text(self, text: str) -> None: ...
    def send_bytes(self, data: bytes) -> None: ...
    def send_json(self, value: Any) -> None: ...
    def send_ping(self, data: bytes | None = None) -> None: ...
    def receive(self) -> WsMessage | None: ...
    def receive_text(self) -> str | None: ...
    def receive_json(self) -> Any | None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...


# ============================================================================
# Middleware
# ============================================================================

class CorsMiddleware:
    """CORS middleware — handles Cross-Origin Resource Sharing."""

    def __init__(
        self,
        allowed_origins: list[str] | None = None,
        allowed_methods: list[str] | None = None,
        allowed_headers: list[str] | None = None,
        expose_headers: list[str] | None = None,
        allow_credentials: bool = False,
        max_age: int = 86400,
    ) -> None: ...
    @staticmethod
    def permissive() -> CorsMiddleware: ...


class RateLimitMiddleware:
    """Rate limiting middleware with multiple algorithms."""

    def __init__(
        self,
        max_requests: int = 100,
        window_secs: int = 60,
        algorithm: str = "sliding",
        key_header: str | None = None,
        skip_paths: list[str] | None = None,
    ) -> None: ...


class SecurityHeadersMiddleware:
    """Security headers middleware."""

    def __init__(
        self,
        hsts: bool = True,
        hsts_max_age: int = 31536000,
        frame_options: str = "DENY",
        content_type_options: bool = True,
        xss_protection: bool = True,
        csp: str | None = None,
    ) -> None: ...
    @staticmethod
    def strict() -> SecurityHeadersMiddleware: ...


class TimeoutMiddleware:
    """Request timeout middleware."""

    def __init__(self, timeout_secs: int = 30) -> None: ...


class CompressionMiddleware:
    """Response compression middleware (gzip)."""

    def __init__(self, min_size: int = 1024) -> None: ...


class RequestIdMiddleware:
    """Request ID middleware for tracing."""

    def __init__(self, header_name: str = "X-Request-ID") -> None: ...


class BasicAuthMiddleware:
    """HTTP Basic Authentication middleware."""

    def __init__(
        self,
        realm: str = "Restricted",
        users: dict[str, str] | None = None,
    ) -> None: ...


class CircuitBreakerMiddleware:
    """Circuit breaker middleware for fault tolerance."""

    def __init__(
        self,
        failure_threshold: int = 5,
        success_threshold: int = 2,
        timeout_secs: int = 30,
        paths: list[str] | None = None,
    ) -> None: ...
    def record_success(self, path: str) -> None: ...
    def record_failure(self, path: str) -> None: ...
    def get_stats(self, path: str) -> dict[str, Any]: ...
    def get_failure_count(self, path: str) -> int: ...


class CacheMiddleware:
    """Caching middleware for GET requests."""

    def __init__(
        self,
        ttl_seconds: int = 60,
        cache_control_respect: bool = True,
        max_cache_size: int = 10000,
        paths: list[str] | None = None,
    ) -> None: ...
    def invalidate(self, route: str, params: str) -> None: ...
    def clear(self) -> None: ...


# ============================================================================
# Health & Reload
# ============================================================================

class HealthCheck:
    """
    Health check / probe state for zero-downtime reload support.

    Tracks service health status, in-flight requests, and uptime.
    Used by Kubernetes-style liveness/readiness/startup probes.
    """

    def __init__(self) -> None: ...
    def status(self) -> str: ...
    def mark_healthy(self) -> None: ...
    def mark_draining(self) -> None: ...
    def mark_unhealthy(self) -> None: ...
    def in_flight(self) -> int: ...
    def uptime_secs(self) -> float: ...
    def is_live(self) -> bool: ...
    def is_ready(self) -> bool: ...
    def to_json(self) -> str: ...
    def add_custom_check(self, name: str) -> None: ...


class ReloadConfig:
    """Configuration for zero-downtime reload behavior."""

    drain_timeout_secs: int
    health_poll_interval_ms: int
    startup_grace_secs: int
    health_probes_enabled: bool
    health_path_prefix: str

    def __init__(
        self,
        drain_timeout_secs: int = 30,
        health_poll_interval_ms: int = 100,
        startup_grace_secs: int = 2,
        health_probes_enabled: bool = True,
        health_path_prefix: str = "/_health",
    ) -> None: ...


class ReloadManager:
    """
    Manager for zero-downtime reloads with health probes.

    Supports graceful reload (drain in-flight, then restart workers),
    hot reload (immediate restart), and health probes for Kubernetes.
    """

    def __init__(self, config: ReloadConfig | None = None) -> None: ...
    def health(self) -> HealthCheck: ...
    def graceful_reload(self) -> None: ...
    def hot_reload(self) -> None: ...
    def shutdown(self) -> None: ...
    def is_draining(self) -> bool: ...
    def status(self) -> str: ...
    def in_flight(self) -> int: ...


# ============================================================================
# Database
# ============================================================================

class PoolConfig:
    """Configuration for the database connection pool."""
    url: str
    max_size: int
    min_idle: int | None
    connect_timeout_secs: int
    idle_timeout_secs: int | None
    max_lifetime_secs: int | None
    test_before_acquire: bool
    keepalive_secs: int | None

    def __init__(
        self,
        url: str,
        max_size: int = 16,
        min_idle: int | None = None,
        connect_timeout_secs: int = 30,
        idle_timeout_secs: int | None = None,
        max_lifetime_secs: int | None = None,
        test_before_acquire: bool = False,
        keepalive_secs: int | None = None,
    ) -> None: ...


class PoolStatus:
    """Status information about the connection pool."""
    size: int
    available: int
    max_size: int


class ConnectionPool:
    """Static connection pool manager."""

    def __init__(self) -> None: ...

    @staticmethod
    def initialize(config: PoolConfig) -> None: ...
    @staticmethod
    def status() -> PoolStatus | None: ...
    @staticmethod
    def is_initialized() -> bool: ...
    @staticmethod
    def close() -> None: ...
    @staticmethod
    def status_for_alias(alias: str) -> PoolStatus | None: ...
    @staticmethod
    def close_all() -> None: ...
    @staticmethod
    def close_alias(alias: str) -> None: ...
    @staticmethod
    def initialize_with_alias(config: PoolConfig, alias: str) -> None: ...


class DbSession:
    """Request-scoped database session."""
    request_id: str

    def begin(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def query(self, sql: str, params: list[Any] | None = None) -> list[dict[str, Any]]: ...
    def query_one(self, sql: str, params: list[Any] | None = None) -> dict[str, Any] | None: ...
    def execute(self, sql: str, params: list[Any] | None = None) -> int: ...
    def execute_many(self, sql: str, params_list: list[list[Any]]) -> int: ...
    def set_auto_commit(self, auto_commit: bool) -> None: ...
    def set_error(self) -> None: ...
    def state(self) -> str: ...


class RowStream:
    """
    Streaming row iterator that yields chunks of rows lazily.

    Allows Python to iterate over large result sets without loading everything into memory.
    """

    def __iter__(self) -> RowStream: ...
    def __next__(self) -> list[dict[str, Any]]: ...
    def is_exhausted(self) -> bool: ...
    def chunk_count(self) -> int: ...


class AnyPool:
    """Generic connection pool interface for multiple database types."""

    def __init__(self, url: str, max_connections: int = 16) -> None: ...
    def query(self, sql: str, params: list[Any] | None = None) -> list[dict[str, Any]]: ...
    def query_one(self, sql: str, params: list[Any] | None = None) -> dict[str, Any] | None: ...
    def execute(self, sql: str, params: list[Any] | None = None) -> int: ...
    def stream_query(self, sql: str, params: list[Any] | None = None, chunk_size: int = 100) -> RowStream: ...
    def close(self) -> None: ...


def get_db(request_id: str) -> DbSession: ...
def finalize_db(request_id: str) -> None: ...
def finalize_db_all(request_id: str) -> None: ...


# ============================================================================
# Realtime: Channel / Topic
# ============================================================================

class ChannelStats:
    """Statistics for a single channel."""
    name: str
    subscriber_count: int
    total_messages: int
    dropped_messages: int
    metadata: dict[str, str]


class Subscriber:
    """Subscriber handle that receives messages from a channel."""
    channel_name: str
    client_id: str
    received_count: int
    missed_count: int

    def try_recv(self) -> str | None: ...
    def drain(self) -> list[str]: ...


class TopicMatcher:
    """Pattern-based topic matching for pub/sub routing."""

    def __init__(self) -> None: ...
    def subscribe(self, pattern: str, client_id: str) -> None: ...
    def unsubscribe(self, pattern: str, client_id: str) -> bool: ...
    def unsubscribe_all(self, client_id: str) -> int: ...
    def match_topic(self, topic: str) -> list[str]: ...
    @staticmethod
    def pattern_matches(pattern: str, topic: str) -> bool: ...
    def patterns(self) -> list[str]: ...
    def subscriber_count(self, pattern: str) -> int: ...


class ChannelManager:
    """High-performance channel manager for pub/sub messaging."""
    topic_matcher: TopicMatcher

    def __init__(self, default_buffer_size: int = 256) -> None: ...
    def create_channel(
        self,
        name: str,
        buffer_size: int | None = None,
        metadata: dict[str, str] | None = None,
    ) -> bool: ...
    def remove_channel(self, name: str) -> bool: ...
    def has_channel(self, name: str) -> bool: ...
    def subscribe(self, channel_name: str, client_id: str) -> Subscriber: ...
    def unsubscribe(self, channel_name: str, client_id: str) -> bool: ...
    def publish(self, channel_name: str, message: str) -> int: ...
    def publish_to_topic(self, topic: str, message: str) -> int: ...
    def get_stats(self, channel_name: str) -> ChannelStats: ...
    def list_channels(self) -> list[str]: ...
    def get_subscribers(self, channel_name: str) -> list[str]: ...
    def channel_count(self) -> int: ...
    def clear(self) -> None: ...


# ============================================================================
# Realtime: Presence
# ============================================================================

class PresenceInfo:
    """Information about a connected client's presence."""
    client_id: str
    channel: str
    metadata: dict[str, str]
    joined_at: float
    last_seen: float

    def __init__(
        self,
        client_id: str,
        channel: str,
        metadata: dict[str, str] | None = None,
    ) -> None: ...


class PresenceDiff:
    """Diff of presence changes (joins and leaves)."""
    joins: list[PresenceInfo]
    leaves: list[str]

    def __init__(self) -> None: ...
    def has_changes(self) -> bool: ...
    def change_count(self) -> int: ...


class PresenceTracker:
    """Track connected clients' presence across channels."""

    def __init__(self) -> None: ...
    def track(
        self,
        channel: str,
        client_id: str,
        metadata: dict[str, str] | None = None,
    ) -> PresenceInfo: ...
    def untrack(self, channel: str, client_id: str) -> bool: ...
    def untrack_all(self, client_id: str) -> list[str]: ...
    def update(self, channel: str, client_id: str, metadata: dict[str, str]) -> bool: ...
    def touch(self, channel: str, client_id: str) -> bool: ...
    def list(self, channel: str) -> list[PresenceInfo]: ...
    def get(self, channel: str, client_id: str) -> PresenceInfo | None: ...
    def count(self, channel: str) -> int: ...
    def flush_diff(self, channel: str) -> PresenceDiff: ...
    def client_channels(self, client_id: str) -> list[str]: ...
    def active_channels(self) -> list[str]: ...
    def total_clients(self) -> int: ...
    def evict_stale(self, timeout_secs: float) -> list[tuple[str, str]]: ...
    def clear(self) -> None: ...


# ============================================================================
# Realtime: Broadcast
# ============================================================================

class BackpressurePolicy(Enum):
    """Policy for handling backpressure when subscribers are slow."""
    DropOldest = 0
    Error = 1


class BroadcastConfig:
    """Configuration for a broadcast channel."""
    buffer_size: int
    policy: BackpressurePolicy
    dedup_enabled: bool
    dedup_window: int

    def __init__(
        self,
        buffer_size: int = 256,
        policy: BackpressurePolicy = BackpressurePolicy.DropOldest,
        dedup_enabled: bool = False,
        dedup_window: int = 1000,
    ) -> None: ...


class BroadcastStats:
    """Statistics for broadcast operations."""
    total_sent: int
    total_dropped: int
    total_deduped: int
    active_subscribers: int
    channel_count: int


class BroadcastSubscriber:
    """Subscriber handle for receiving broadcast messages."""
    channel_name: str
    received_count: int
    lagged_count: int

    def try_recv(self) -> str | None: ...
    def drain(self) -> list[str]: ...


class RealtimeBroadcast:
    """Backpressure-aware broadcast system."""

    def __init__(self) -> None: ...
    def create(self, name: str, config: BroadcastConfig | None = None) -> bool: ...
    def remove(self, name: str) -> bool: ...
    def subscribe(self, name: str) -> BroadcastSubscriber: ...
    def send(self, name: str, message: str, message_id: str | None = None) -> int: ...
    def send_many(self, names: list[str], message: str) -> dict[str, int]: ...
    def stats(self, name: str) -> BroadcastStats: ...
    def global_stats(self) -> BroadcastStats: ...
    def list_channels(self) -> list[str]: ...
    def has_channel(self, name: str) -> bool: ...
    def clear(self) -> None: ...


# ============================================================================
# Realtime: Heartbeat
# ============================================================================

class HeartbeatConfig:
    """Configuration for heartbeat monitoring."""
    interval_secs: float
    timeout_secs: float
    max_retries: int
    sse_retry_ms: int
    send_keepalive: bool

    def __init__(
        self,
        interval_secs: float = 30.0,
        timeout_secs: float = 90.0,
        max_retries: int = 5,
        sse_retry_ms: int = 3000,
        send_keepalive: bool = True,
    ) -> None: ...


class HeartbeatStats:
    """Stats for heartbeat monitoring."""
    monitored_clients: int
    total_pings: int
    total_pongs: int
    total_timeouts: int
    timed_out_clients: int


class HeartbeatMonitor:
    """Server-side heartbeat monitor for SSE and WebSocket connections."""
    config: HeartbeatConfig

    def __init__(self, config: HeartbeatConfig | None = None) -> None: ...
    def register(self, client_id: str, last_event_id: str | None = None) -> None: ...
    def unregister(self, client_id: str) -> bool: ...
    def ping(self, client_id: str) -> bool: ...
    def pong(self, client_id: str) -> bool: ...
    def check_timeouts(self) -> list[str]: ...
    def is_timed_out(self, client_id: str) -> bool: ...
    def is_alive(self, client_id: str) -> bool: ...
    def get_dead_clients(self) -> list[str]: ...
    def evict_dead(self) -> list[str]: ...
    def set_last_event_id(self, client_id: str, event_id: str) -> bool: ...
    def get_last_event_id(self, client_id: str) -> str | None: ...
    def clients_needing_ping(self) -> list[str]: ...
    def sse_keepalive_comment(self) -> str: ...
    def sse_retry_field(self) -> str: ...
    def sse_heartbeat_event(self) -> str: ...
    def retry_count(self, client_id: str) -> int: ...
    def stats(self) -> HeartbeatStats: ...
    def client_ids(self) -> list[str]: ...
    def client_info(self) -> dict[str, dict[str, str]]: ...
    def clear(self) -> None: ...
    def client_count(self) -> int: ...


# ============================================================================
# HTTP Client
# ============================================================================

class ClientResponse:
    """Response from an HTTP request."""
    status: int

    def headers(self) -> dict[str, str]: ...
    def text(self) -> str: ...
    def json(self) -> Any: ...
    def bytes(self) -> bytes: ...


class HttpClient:
    """Async HTTP client backed by reqwest with Rust-level connection pooling."""

    def __init__(
        self,
        base_url: str | None = None,
        timeout: int = 30,
        max_connections: int = 20,
    ) -> None: ...
    def get(
        self,
        url: str,
        headers: dict[str, str] | None = None,
        params: dict[str, Any] | None = None,
    ) -> ClientResponse: ...
    def post(
        self,
        url: str,
        headers: dict[str, str] | None = None,
        json: str | None = None,
        body: bytes | None = None,
    ) -> ClientResponse: ...
    def put(
        self,
        url: str,
        headers: dict[str, str] | None = None,
        json: str | None = None,
        body: bytes | None = None,
    ) -> ClientResponse: ...
    def patch(
        self,
        url: str,
        headers: dict[str, str] | None = None,
        json: str | None = None,
        body: bytes | None = None,
    ) -> ClientResponse: ...
    def delete(
        self,
        url: str,
        headers: dict[str, str] | None = None,
    ) -> ClientResponse: ...


# ============================================================================
# Telemetry / Metrics
# ============================================================================

class MetricsRegistry:
    """Prometheus-compatible metrics registry."""

    def __init__(self) -> None: ...
    def counter_inc(
        self,
        name: str,
        labels: str | None = None,
        value: int = 1,
    ) -> None: ...
    def gauge_set(
        self,
        name: str,
        value: float,
        labels: str | None = None,
    ) -> None: ...
    def gauge_inc(self, name: str, labels: str | None = None) -> None: ...
    def gauge_dec(self, name: str, labels: str | None = None) -> None: ...
    def histogram_observe(
        self,
        name: str,
        value: float,
        labels: str | None = None,
    ) -> None: ...
    def set_help(self, name: str, help: str) -> None: ...
    def render(self) -> str: ...


# ============================================================================
# Fast Path: Static Files
# ============================================================================

class StaticFileHandler:
    """
    Static file serving with memory-mapped files for zero-copy performance.

    Serves files from a directory with caching and optional SPA fallback.
    """

    directory: str
    prefix: str

    def __init__(
        self,
        directory: str,
        prefix: str = "/static",
        index: str = "index.html",
        spa: bool = False,
        cache_max_age: int | None = None,
    ) -> None: ...
    def serve_file(
        self,
        path: str,
        if_none_match: str | None = None,
    ) -> tuple[bytes, str, str, int]: ...
    def clear_cache_py(self) -> None: ...


# ============================================================================
# Utils: String Helpers
# ============================================================================

def slugify(text: str, separator: str = "-") -> str: ...
def truncate(text: str, max_len: int, suffix: str = "...") -> str: ...
def mask_email(email: str) -> str: ...
def mask_phone(phone: str, keep_last: int = 4) -> str: ...
def mask_string(text: str, keep_start: int = 1, keep_end: int = 1) -> str: ...
def snake_to_camel(text: str, upper_first: bool = False) -> str: ...
def camel_to_snake(text: str) -> str: ...
def keys_to_camel(data: dict[str, Any], upper_first: bool = False) -> dict[str, Any]: ...
def keys_to_snake(data: dict[str, Any]) -> dict[str, Any]: ...
def pad_left(text: str, width: int, pad_char: str = " ") -> str: ...
def pad_right(text: str, width: int, pad_char: str = " ") -> str: ...
def word_count(text: str) -> int: ...
def is_url_safe(text: str) -> bool: ...


# ============================================================================
# Utils: Pagination
# ============================================================================

class PageInfo:
    """Pagination metadata (immutable, computed in Rust)."""
    total: int
    page: int
    per_page: int
    total_pages: int
    has_next: bool
    has_prev: bool
    offset: int
    from_item: int
    to_item: int

    def to_dict(self) -> dict[str, Any]: ...


def paginate(total: int, page: int = 1, per_page: int = 20) -> PageInfo: ...
def encode_cursor(offset: int) -> str: ...
def decode_cursor(cursor: str) -> int: ...


# ============================================================================
# Utils: Crypto / Encoding / IDs
# ============================================================================

def random_token(length: int = 32) -> str: ...
def random_bytes(n: int) -> bytes: ...
def hmac_sha256_hex(key: str, data: str) -> str: ...
def hmac_sha256_bytes(key: bytes, data: bytes) -> bytes: ...
def sha256_hex(data: str) -> str: ...
def secure_compare(a: bytes, b: bytes) -> bool: ...
def b64_encode(data: bytes) -> str: ...
def b64_decode(data: str) -> bytes | None: ...
def b64url_encode(data: bytes) -> str: ...
def b64url_decode(data: str) -> bytes | None: ...
def uuid_v4() -> str: ...
def uuid_v7() -> str: ...
def fast_hash(data: str) -> int: ...
def fast_hash_bytes(data: bytes) -> int: ...
def jwt_sign_rs256(payload: str, private_key_pem: str) -> str: ...
def jwt_verify_rs256(token: str, public_key_pem: str) -> str | None: ...
def jwt_sign_es256(payload: str, private_key_pem: str) -> str: ...
def jwt_verify_es256(token: str, public_key_pem: str) -> str | None: ...


# ============================================================================
# Utils: Time Helpers
# ============================================================================

def now_ms() -> int: ...
def now_sec() -> int: ...
def now_iso() -> str: ...
def format_timestamp(ts_secs: int) -> str: ...
def parse_iso(s: str) -> int | None: ...
def relative_time(ts_secs: int) -> str: ...
def elapsed_ms(start_ms: int) -> int: ...
def ms_to_sec(ms: int) -> int: ...
def sec_to_ms(sec: int) -> int: ...


# ============================================================================
# gRPC
# ============================================================================

class GrpcConfig:
    """Configuration for gRPC clients and servers."""
    host: str
    port: int

    def __init__(self, host: str = "0.0.0.0", port: int = 50051) -> None: ...


class GrpcServer:
    """gRPC server implementation."""

    def __init__(self, config: GrpcConfig | None = None) -> None: ...
    def address(self) -> str: ...
    def is_running(self) -> bool: ...


# ============================================================================
# Redis
# ============================================================================

class RedisPool:
    """Redis connection pool with async support."""

    def __init__(self, url: str, pool_size: int = 16) -> None: ...
    def get(self, key: str) -> str | None: ...
    def set(self, key: str, value: str, ex: int | None = None) -> None: ...
    def delete(self, key: str) -> int: ...
    def expire(self, key: str, seconds: int) -> bool: ...
    def incr(self, key: str) -> int: ...
    def publish(self, channel: str, message: str) -> int: ...
    def ping(self) -> bool: ...
