from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Dict, List

class Request:
    path: str
    query_params: Dict[str, str]
    headers: Dict[str, str]
    body: Any

    async def __call__(self, *args, **kwds): ...

class Response:
    def response_bytes(self, status: int, headers: list[tuple[str, str]], body: bytes) -> None: ...

@dataclass
class Server:
    router: Router
    websocket_router: Any
    startup_handler: Any
    shutdown_handler: Any

    def add_route(self, route: Route) -> None: ...
    def set_router(self, router: Router) -> None: ...
    def start(self, socket: SocketHeld, worker: int, max_blocking_threads: int) -> None: ...
    def enable_http2(self) -> None: ...

class Route:
    path: str
    function: Callable[[Request, Response], Any]
    method: str
    doc: str | None = None

    def matches(self, path: str, method: str) -> str: ...
    def clone_route(self) -> Route: ...
    def update_path(self, new_path: str) -> None: ...
    def update_method(self, new_method: str) -> None: ...
    def is_valid(self) -> bool: ...
    def get_path_parans(self) -> List[str]: ...
    def has_parameters(self) -> bool: ...
    def normalized_path(self) -> str: ...
    def same_handler(self, other: Route) -> bool: ...

class Router:
    routes: List[Route]

    def add_route(self, route: Route) -> None: ...
    def remove_route(self, path: str, method: str) -> bool: ...
    def get_route(self, path: str, method) -> Route | None: ...
    def get_routes_by_path(self, path: str) -> List[Route]: ...
    def get_routes_by_method(self, method: str) -> List[Route]: ...
    def extend_route(self, routes: List[Route]) -> None: ...

@dataclass
class SocketHeld:
    socket: Any

@dataclass
class Header:

    def get(self, key: str) -> str | None: ...
    def get_all(self, key: str) -> List[str]: ...
    def keys(self) -> List[str]: ...
    def values(self) -> List[str]: ...
    def items(self) -> Dict[str, str]: ...
