version: "3"
services:
  template-service:
    image: template:latest
    container_name: template
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:5000
    networks:
      - base
    command: gunicorn --bind 0.0.0.0:5000 main:app -c conf/gunicorn.py

networks:
  base:
    external: true
