FROM python:3.12-slim AS build

WORKDIR /src

COPY mkdocs.yml ./
COPY docs ./docs

RUN pip install --no-cache-dir mkdocs mkdocs-material \
 && mkdocs build --strict


FROM python:3.12-slim

WORKDIR /site

COPY --from=build /src/site .

USER 65532:65532

EXPOSE 8080

CMD ["python", "-m", "http.server", "8080"]
