name: codspeed-benchmarks

on:
  push:
    branches:
      - "stag" # or "master"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:    

  benchmarks:
    runs-on: ubuntu-latest
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry maturin
          poetry export --with test --with dev --without-hashes --output requirements.txt
          pip install -r requirements.txt
          pip install -e .
      - name: Add macos target
        if: matrix.os == 'macos'
        run: rustup target add aarch64-apple-darwin
      - name: Setup Rust part of the project
        run: |
          maturin build -i python --universal2 --out dist
          pip install --no-index --find-links=dist/ pyfast

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        env:
          REDIS_URL: redis://redis:6379
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest tests --codspeed
